#!/bin/bash
#TODO check network wso2am exist
#IF not docker network create wso2am
#TODO check if old docker named so exist
#IF yes docker rm analytics
docker run --name analytics --network wso2am -p 9444:9444 -i nrb/wso2am-analytics
